# Generated by Django 5.2.16 on 2026-07-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0013_applicationconfiguration_llm_request_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfiguration',
            name='llm_hybrid_retrieval',
            field=models.BooleanField(default=False, null=True, verbose_name='Enables hybrid retrieval for AI chat'),
        ),
    ]
